### ISSUE TITLE
代码没有包含响应包导致错误

### ISSUE THREAD

**Issue by GGmemeda** [maptalks/maptalks.e3#13]
引入资源出错，导致找不到
import * as maptalks from 'maptalks';
import * as echarts from 'echarts';

**Comment by fuzhenn** [comment]
import方式一直能正常使用，请提供一下具体的报错信息方便定位问题。

**Comment by GGmemeda** [comment]
![3 VNA L`~97ZN6T75XMOM N](https://user-images.githubusercontent.com/24998007/169502550-feff219a-d563-4f4a-8b10-fa21350e1d41.png)

这是demo报错，我发现是因为没有maptalks.Layer导致的

**Comment by fuzhenn** [comment]
噢，这是maptalks.e3打包设置的问题导致的，我刚刚重新打包发布了，请更新到0.5.2后再看看问题好了没有。
